name: medtrack
description: Medtrack's Android app and Web platform
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^0.13.5
  alarm: ^1.0.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  intl: ^0.18.1
  qr_flutter: ^4.0.0
  path_provider: ^2.0.14
  share: ^2.0.4
  mobile_scanner: ^3.2.0
  flutter_barcode_scanner: ^2.0.0
  settings_ui: ^2.0.2
  flutter_speed_dial: ^6.2.0
  file_picker: ^5.3.0
  introduction_screen: ^3.1.8
  shared_preferences: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  hive_generator: ^2.0.0
  build_runner: ^2.2.3

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png
    - assets/images/healthcare.png
    - assets/images/report.png
    - assets/images/certificate.png
    - assets/images/medicine.png
    - sounds/mozart.mp3
    - sounds/nokia.mp3
    - sounds/one_piece.mp3
    - sounds/star_wars.mp3

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware
